var translationsSW = {
    CREATE_SUCCESS:"Rekodi imeongezwa kwenye mfumo",
    UPDATE_SUCCESS:"Rekodi imebadilishwa",
    DELETE_SUCCESS:"Rekodi imefutwa",
    TITLE: "Cheo",
    NAME: "Jina",
    PRODUCTS: "Bidhaa",
    CREATE:"Ongeza {{item}}",
    UPDATE:"Sasisha {{item}}",
    CUSTOMER:"Mteja",
    CUSTOMERS:"Wateja",
    NET_AMOUNT:"Jumla Ndogo",
    VAT:"VAT",
    TOTAL:"Jumla kuu",
    SUB_TOTAL:'Jumla ndogo',
    REMOVE:'Ondoa',
    PAID:'Amelipa kwa:',
    ITEM:'Bidhaa',
    PRICE:'Bei',
    DATE:'Tarehe',
    QTY:'Idadi',
    SNO:'Nambari',
    TAX:'Kodi',
    RECEIPT:'Stakabadhi',
};

